prefix = "employeesystem"
location = "East US"
admin_username = "jaylonjones"
admin_password = "Panthers27!"
sql_db_name = "EmployeeSystemOnboardingDatabaseSQL"
certificate_password = "Panthers27"
ssl_certificate = ""
